"""
Complete Pokemon Database for the Legion Discord Bot
Contains comprehensive Pokemon data for all generations.
Auto-generated database with official artwork URLs.
"""

POKEMON_DATABASE = {
    1: {
        "name": "Bulbasaur",
        "types": ['Grass', 'Poison'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 45, 'attack': 49, 'defense': 49, 'sp_attack': 65, 'sp_defense': 65, 'speed': 45, 'total': 318},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
    },
    2: {
        "name": "Ivysaur",
        "types": ['Grass', 'Poison'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 60, 'attack': 62, 'defense': 63, 'sp_attack': 80, 'sp_defense': 80, 'speed': 60, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
    },
    3: {
        "name": "Venusaur",
        "types": ['Grass', 'Poison'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 80, 'attack': 82, 'defense': 83, 'sp_attack': 100, 'sp_defense': 100, 'speed': 80, 'total': 525},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
    },
    4: {
        "name": "Charmander",
        "types": ['Fire'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 39, 'attack': 52, 'defense': 43, 'sp_attack': 60, 'sp_defense': 50, 'speed': 65, 'total': 309},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
    },
    5: {
        "name": "Charmeleon",
        "types": ['Fire'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 58, 'attack': 64, 'defense': 58, 'sp_attack': 80, 'sp_defense': 65, 'speed': 80, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
    },
    6: {
        "name": "Charizard",
        "types": ['Fire', 'Flying'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 78, 'attack': 84, 'defense': 78, 'sp_attack': 109, 'sp_defense': 85, 'speed': 100, 'total': 534},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
    },
    7: {
        "name": "Squirtle",
        "types": ['Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 44, 'attack': 48, 'defense': 65, 'sp_attack': 50, 'sp_defense': 64, 'speed': 43, 'total': 314},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
    },
    8: {
        "name": "Wartortle",
        "types": ['Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 59, 'attack': 63, 'defense': 80, 'sp_attack': 65, 'sp_defense': 80, 'speed': 58, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
    },
    9: {
        "name": "Blastoise",
        "types": ['Water'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 79, 'attack': 83, 'defense': 100, 'sp_attack': 85, 'sp_defense': 105, 'speed': 78, 'total': 530},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
    },
    10: {
        "name": "Caterpie",
        "types": ['Bug'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 45, 'attack': 30, 'defense': 35, 'sp_attack': 20, 'sp_defense': 20, 'speed': 45, 'total': 195},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
    },
    11: {
        "name": "Metapod",
        "types": ['Bug'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 50, 'attack': 20, 'defense': 55, 'sp_attack': 25, 'sp_defense': 25, 'speed': 30, 'total': 205},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
    },
    12: {
        "name": "Butterfree",
        "types": ['Bug', 'Flying'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 60, 'attack': 45, 'defense': 50, 'sp_attack': 90, 'sp_defense': 80, 'speed': 70, 'total': 395},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
    },
    13: {
        "name": "Weedle",
        "types": ['Bug', 'Poison'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 40, 'attack': 35, 'defense': 30, 'sp_attack': 20, 'sp_defense': 20, 'speed': 50, 'total': 195},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
    },
    14: {
        "name": "Kakuna",
        "types": ['Bug', 'Poison'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 45, 'attack': 25, 'defense': 50, 'sp_attack': 25, 'sp_defense': 25, 'speed': 35, 'total': 205},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
    },
    15: {
        "name": "Beedrill",
        "types": ['Bug', 'Poison'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 65, 'attack': 90, 'defense': 40, 'sp_attack': 45, 'sp_defense': 80, 'speed': 75, 'total': 395},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
    },
    16: {
        "name": "Pidgey",
        "types": ['Normal', 'Flying'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 40, 'attack': 45, 'defense': 40, 'sp_attack': 35, 'sp_defense': 35, 'speed': 56, 'total': 251},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
    },
    17: {
        "name": "Pidgeotto",
        "types": ['Normal', 'Flying'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 63, 'attack': 60, 'defense': 55, 'sp_attack': 50, 'sp_defense': 50, 'speed': 71, 'total': 349},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
    },
    18: {
        "name": "Pidgeot",
        "types": ['Normal', 'Flying'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 83, 'attack': 80, 'defense': 75, 'sp_attack': 70, 'sp_defense': 70, 'speed': 101, 'total': 479},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
    },
    19: {
        "name": "Rattata",
        "types": ['Normal'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 30, 'attack': 56, 'defense': 35, 'sp_attack': 25, 'sp_defense': 35, 'speed': 72, 'total': 253},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
    },
    20: {
        "name": "Raticate",
        "types": ['Normal'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 55, 'attack': 81, 'defense': 60, 'sp_attack': 50, 'sp_defense': 70, 'speed': 97, 'total': 413},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
    },
    25: {
        "name": "Pikachu",
        "types": ['Electric'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 35, 'attack': 55, 'defense': 40, 'sp_attack': 50, 'sp_defense': 50, 'speed': 90, 'total': 320},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
    },
    26: {
        "name": "Raichu",
        "types": ['Electric'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 60, 'attack': 90, 'defense': 55, 'sp_attack': 90, 'sp_defense': 80, 'speed': 110, 'total': 485},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
    },
    129: {
        "name": "Magikarp",
        "types": ['Water'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 20, 'attack': 10, 'defense': 55, 'sp_attack': 15, 'sp_defense': 20, 'speed': 80, 'total': 200},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png",
    },
    130: {
        "name": "Gyarados",
        "types": ['Water', 'Flying'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 95, 'attack': 125, 'defense': 79, 'sp_attack': 60, 'sp_defense': 100, 'speed': 81, 'total': 540},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
    },
    131: {
        "name": "Lapras",
        "types": ['Water', 'Ice'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 130, 'attack': 85, 'defense': 80, 'sp_attack': 85, 'sp_defense': 95, 'speed': 60, 'total': 535},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
    },
    133: {
        "name": "Eevee",
        "types": ['Normal'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 55, 'attack': 55, 'defense': 50, 'sp_attack': 45, 'sp_defense': 65, 'speed': 55, 'total': 325},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
    },
    134: {
        "name": "Vaporeon",
        "types": ['Water'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 130, 'attack': 65, 'defense': 60, 'sp_attack': 110, 'sp_defense': 95, 'speed': 65, 'total': 525},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
    },
    135: {
        "name": "Jolteon",
        "types": ['Electric'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 65, 'attack': 65, 'defense': 60, 'sp_attack': 110, 'sp_defense': 95, 'speed': 130, 'total': 525},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png",
    },
    136: {
        "name": "Flareon",
        "types": ['Fire'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 65, 'attack': 130, 'defense': 60, 'sp_attack': 95, 'sp_defense': 110, 'speed': 65, 'total': 525},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png",
    },
    138: {
        "name": "Omanyte",
        "types": ['Rock', 'Water'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 35, 'attack': 40, 'defense': 100, 'sp_attack': 90, 'sp_defense': 55, 'speed': 35, 'total': 355},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png",
    },
    139: {
        "name": "Omastar",
        "types": ['Rock', 'Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 70, 'attack': 60, 'defense': 125, 'sp_attack': 115, 'sp_defense': 70, 'speed': 55, 'total': 495},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png",
    },
    140: {
        "name": "Kabuto",
        "types": ['Rock', 'Water'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 30, 'attack': 80, 'defense': 90, 'sp_attack': 55, 'sp_defense': 45, 'speed': 55, 'total': 355},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png",
    },
    141: {
        "name": "Kabutops",
        "types": ['Rock', 'Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 60, 'attack': 115, 'defense': 105, 'sp_attack': 65, 'sp_defense': 70, 'speed': 80, 'total': 495},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png",
    },
    142: {
        "name": "Aerodactyl",
        "types": ['Rock', 'Flying'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 80, 'attack': 105, 'defense': 65, 'sp_attack': 60, 'sp_defense': 75, 'speed': 130, 'total': 515},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png",
    },
    143: {
        "name": "Snorlax",
        "types": ['Normal'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 160, 'attack': 110, 'defense': 65, 'sp_attack': 65, 'sp_defense': 110, 'speed': 30, 'total': 540},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
    },
    144: {
        "name": "Articuno",
        "types": ['Ice', 'Flying'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 90, 'attack': 85, 'defense': 100, 'sp_attack': 95, 'sp_defense': 125, 'speed': 85, 'total': 580},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
    },
    145: {
        "name": "Zapdos",
        "types": ['Electric', 'Flying'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 90, 'attack': 90, 'defense': 85, 'sp_attack': 125, 'sp_defense': 90, 'speed': 100, 'total': 580},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
    },
    146: {
        "name": "Moltres",
        "types": ['Fire', 'Flying'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 1,
        "description": "A rare Pokemon from Generation 1.",
        "stats": {'hp': 90, 'attack': 100, 'defense': 90, 'sp_attack': 125, 'sp_defense': 85, 'speed': 90, 'total': 580},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png",
    },
    147: {
        "name": "Dratini",
        "types": ['Dragon'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 1,
        "description": "A common Pokemon from Generation 1.",
        "stats": {'hp': 41, 'attack': 64, 'defense': 45, 'sp_attack': 50, 'sp_defense': 50, 'speed': 50, 'total': 300},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
    },
    148: {
        "name": "Dragonair",
        "types": ['Dragon'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 1,
        "description": "A uncommon Pokemon from Generation 1.",
        "stats": {'hp': 61, 'attack': 84, 'defense': 65, 'sp_attack': 70, 'sp_defense': 70, 'speed': 70, 'total': 420},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png",
    },
    149: {
        "name": "Dragonite",
        "types": ['Dragon', 'Flying'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 1,
        "description": "A legendary Pokemon from Generation 1.",
        "stats": {'hp': 91, 'attack': 134, 'defense': 95, 'sp_attack': 100, 'sp_defense': 100, 'speed': 80, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
    },
    150: {
        "name": "Mewtwo",
        "types": ['Psychic'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 1,
        "description": "A legendary Pokemon from Generation 1.",
        "stats": {'hp': 106, 'attack': 110, 'defense': 90, 'sp_attack': 154, 'sp_defense': 90, 'speed': 130, 'total': 680},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
    },
    151: {
        "name": "Mew",
        "types": ['Psychic'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 1,
        "description": "A legendary Pokemon from Generation 1.",
        "stats": {'hp': 100, 'attack': 100, 'defense': 100, 'sp_attack': 100, 'sp_defense': 100, 'speed': 100, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
    },
    152: {
        "name": "Chikorita",
        "types": ['Grass'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 45, 'attack': 49, 'defense': 65, 'sp_attack': 49, 'sp_defense': 65, 'speed': 45, 'total': 318},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/152.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/152.png",
    },
    153: {
        "name": "Bayleef",
        "types": ['Grass'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 60, 'attack': 62, 'defense': 80, 'sp_attack': 63, 'sp_defense': 80, 'speed': 60, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/153.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/153.png",
    },
    154: {
        "name": "Meganium",
        "types": ['Grass'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 2,
        "description": "A rare Pokemon from Generation 2.",
        "stats": {'hp': 80, 'attack': 82, 'defense': 100, 'sp_attack': 83, 'sp_defense': 100, 'speed': 80, 'total': 525},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/154.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/154.png",
    },
    155: {
        "name": "Cyndaquil",
        "types": ['Fire'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 39, 'attack': 52, 'defense': 43, 'sp_attack': 60, 'sp_defense': 50, 'speed': 65, 'total': 309},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/155.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/155.png",
    },
    156: {
        "name": "Quilava",
        "types": ['Fire'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 58, 'attack': 64, 'defense': 58, 'sp_attack': 80, 'sp_defense': 65, 'speed': 80, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/156.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/156.png",
    },
    157: {
        "name": "Typhlosion",
        "types": ['Fire'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 2,
        "description": "A rare Pokemon from Generation 2.",
        "stats": {'hp': 78, 'attack': 84, 'defense': 78, 'sp_attack': 109, 'sp_defense': 85, 'speed': 100, 'total': 534},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/157.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/157.png",
    },
    158: {
        "name": "Totodile",
        "types": ['Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 50, 'attack': 65, 'defense': 64, 'sp_attack': 44, 'sp_defense': 48, 'speed': 43, 'total': 314},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/158.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/158.png",
    },
    159: {
        "name": "Croconaw",
        "types": ['Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 65, 'attack': 80, 'defense': 80, 'sp_attack': 59, 'sp_defense': 63, 'speed': 58, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/159.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/159.png",
    },
    160: {
        "name": "Feraligatr",
        "types": ['Water'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 2,
        "description": "A rare Pokemon from Generation 2.",
        "stats": {'hp': 85, 'attack': 105, 'defense': 100, 'sp_attack': 79, 'sp_defense': 83, 'speed': 78, 'total': 530},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/160.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/160.png",
    },
    161: {
        "name": "Sentret",
        "types": ['Normal'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 2,
        "description": "A common Pokemon from Generation 2.",
        "stats": {'hp': 35, 'attack': 46, 'defense': 34, 'sp_attack': 35, 'sp_defense': 45, 'speed': 20, 'total': 215},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/161.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/161.png",
    },
    162: {
        "name": "Furret",
        "types": ['Normal'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 85, 'attack': 76, 'defense': 64, 'sp_attack': 45, 'sp_defense': 55, 'speed': 90, 'total': 415},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/162.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/162.png",
    },
    163: {
        "name": "Hoothoot",
        "types": ['Normal', 'Flying'],
        "rarity": "Common",
        "catch_rate": 0.75,
        "generation": 2,
        "description": "A common Pokemon from Generation 2.",
        "stats": {'hp': 60, 'attack': 30, 'defense': 30, 'sp_attack': 36, 'sp_defense': 56, 'speed': 50, 'total': 262},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/163.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/163.png",
    },
    164: {
        "name": "Noctowl",
        "types": ['Normal', 'Flying'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 2,
        "description": "A uncommon Pokemon from Generation 2.",
        "stats": {'hp': 100, 'attack': 50, 'defense': 50, 'sp_attack': 86, 'sp_defense': 96, 'speed': 70, 'total': 452},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/164.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/164.png",
    },
    243: {
        "name": "Raikou",
        "types": ['Electric'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 2,
        "description": "A rare Pokemon from Generation 2.",
        "stats": {'hp': 90, 'attack': 85, 'defense': 75, 'sp_attack': 115, 'sp_defense': 100, 'speed': 115, 'total': 580},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/243.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/243.png",
    },
    244: {
        "name": "Entei",
        "types": ['Fire'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 2,
        "description": "A rare Pokemon from Generation 2.",
        "stats": {'hp': 115, 'attack': 115, 'defense': 85, 'sp_attack': 90, 'sp_defense': 75, 'speed': 100, 'total': 580},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/244.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/244.png",
    },
    245: {
        "name": "Suicune",
        "types": ['Water'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 2,
        "description": "A rare Pokemon from Generation 2.",
        "stats": {'hp': 100, 'attack': 75, 'defense': 115, 'sp_attack': 90, 'sp_defense': 115, 'speed': 85, 'total': 580},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/245.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/245.png",
    },
    249: {
        "name": "Lugia",
        "types": ['Psychic', 'Flying'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 2,
        "description": "A legendary Pokemon from Generation 2.",
        "stats": {'hp': 106, 'attack': 90, 'defense': 130, 'sp_attack': 90, 'sp_defense': 154, 'speed': 110, 'total': 680},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/249.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/249.png",
    },
    250: {
        "name": "Ho-Oh",
        "types": ['Fire', 'Flying'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 2,
        "description": "A legendary Pokemon from Generation 2.",
        "stats": {'hp': 106, 'attack': 130, 'defense': 90, 'sp_attack': 110, 'sp_defense': 154, 'speed': 90, 'total': 680},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/250.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/250.png",
    },
    251: {
        "name": "Celebi",
        "types": ['Psychic', 'Grass'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 2,
        "description": "A legendary Pokemon from Generation 2.",
        "stats": {'hp': 100, 'attack': 100, 'defense': 100, 'sp_attack': 100, 'sp_defense': 100, 'speed': 100, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/251.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/251.png",
    },
    252: {
        "name": "Treecko",
        "types": ['Grass'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 3,
        "description": "A uncommon Pokemon from Generation 3.",
        "stats": {'hp': 40, 'attack': 45, 'defense': 35, 'sp_attack': 65, 'sp_defense': 55, 'speed': 70, 'total': 310},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/252.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/252.png",
    },
    253: {
        "name": "Grovyle",
        "types": ['Grass'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 3,
        "description": "A uncommon Pokemon from Generation 3.",
        "stats": {'hp': 50, 'attack': 65, 'defense': 45, 'sp_attack': 85, 'sp_defense': 65, 'speed': 95, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/253.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/253.png",
    },
    254: {
        "name": "Sceptile",
        "types": ['Grass'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 3,
        "description": "A rare Pokemon from Generation 3.",
        "stats": {'hp': 70, 'attack': 85, 'defense': 65, 'sp_attack': 105, 'sp_defense': 85, 'speed': 120, 'total': 530},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/254.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/254.png",
    },
    255: {
        "name": "Torchic",
        "types": ['Fire'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 3,
        "description": "A uncommon Pokemon from Generation 3.",
        "stats": {'hp': 45, 'attack': 60, 'defense': 40, 'sp_attack': 70, 'sp_defense': 50, 'speed': 45, 'total': 310},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/255.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png",
    },
    256: {
        "name": "Combusken",
        "types": ['Fire', 'Fighting'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 3,
        "description": "A uncommon Pokemon from Generation 3.",
        "stats": {'hp': 60, 'attack': 85, 'defense': 60, 'sp_attack': 85, 'sp_defense': 60, 'speed': 55, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/256.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/256.png",
    },
    257: {
        "name": "Blaziken",
        "types": ['Fire', 'Fighting'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 3,
        "description": "A rare Pokemon from Generation 3.",
        "stats": {'hp': 80, 'attack': 120, 'defense': 70, 'sp_attack': 110, 'sp_defense': 70, 'speed': 80, 'total': 530},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/257.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/257.png",
    },
    258: {
        "name": "Mudkip",
        "types": ['Water'],
        "rarity": "Uncommon",
        "catch_rate": 0.45,
        "generation": 3,
        "description": "A uncommon Pokemon from Generation 3.",
        "stats": {'hp': 50, 'attack': 70, 'defense': 50, 'sp_attack': 50, 'sp_defense': 50, 'speed': 40, 'total': 310},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/258.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png",
    },
    259: {
        "name": "Marshtomp",
        "types": ['Water', 'Ground'],
        "rarity": "Uncommon",
        "catch_rate": 0.5,
        "generation": 3,
        "description": "A uncommon Pokemon from Generation 3.",
        "stats": {'hp': 70, 'attack': 85, 'defense': 70, 'sp_attack': 60, 'sp_defense': 70, 'speed': 50, 'total': 405},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/259.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/259.png",
    },
    260: {
        "name": "Swampert",
        "types": ['Water', 'Ground'],
        "rarity": "Rare",
        "catch_rate": 0.2,
        "generation": 3,
        "description": "A rare Pokemon from Generation 3.",
        "stats": {'hp': 100, 'attack': 110, 'defense': 90, 'sp_attack': 85, 'sp_defense': 90, 'speed': 60, 'total': 535},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/260.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png",
    },
    380: {
        "name": "Latias",
        "types": ['Dragon', 'Psychic'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 80, 'attack': 80, 'defense': 90, 'sp_attack': 110, 'sp_defense': 130, 'speed': 110, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/380.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/380.png",
    },
    381: {
        "name": "Latios",
        "types": ['Dragon', 'Psychic'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 80, 'attack': 90, 'defense': 80, 'sp_attack': 130, 'sp_defense': 110, 'speed': 110, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/381.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/381.png",
    },
    382: {
        "name": "Kyogre",
        "types": ['Water'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 100, 'attack': 100, 'defense': 90, 'sp_attack': 150, 'sp_defense': 140, 'speed': 90, 'total': 670},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/382.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/382.png",
    },
    383: {
        "name": "Groudon",
        "types": ['Ground'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 100, 'attack': 150, 'defense': 140, 'sp_attack': 100, 'sp_defense': 90, 'speed': 90, 'total': 670},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/383.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/383.png",
    },
    384: {
        "name": "Rayquaza",
        "types": ['Dragon', 'Flying'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 105, 'attack': 150, 'defense': 90, 'sp_attack': 150, 'sp_defense': 90, 'speed': 95, 'total': 680},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/384.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/384.png",
    },
    385: {
        "name": "Jirachi",
        "types": ['Steel', 'Psychic'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 100, 'attack': 100, 'defense': 100, 'sp_attack': 100, 'sp_defense': 100, 'speed': 100, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/385.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/385.png",
    },
    386: {
        "name": "Deoxys",
        "types": ['Psychic'],
        "rarity": "Legendary",
        "catch_rate": 0.05,
        "generation": 3,
        "description": "A legendary Pokemon from Generation 3.",
        "stats": {'hp': 50, 'attack': 150, 'defense': 50, 'sp_attack': 150, 'sp_defense': 50, 'speed': 150, 'total': 600},
        "image_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/386.png",
        "sprite_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/386.png",
    },
}


# Rarity distribution weights
RARITY_WEIGHTS = {
    "Common": 0.45,      # 45%
    "Uncommon": 0.35,    # 35%
    "Rare": 0.15,        # 15%
    "Legendary": 0.05    # 5%
}

# Type color mapping for embeds
TYPE_COLORS = {
    "Normal": 0xA8A878, "Fire": 0xF08030, "Water": 0x6890F0, "Electric": 0xF8D030,
    "Grass": 0x78C850, "Ice": 0x98D8D8, "Fighting": 0xC03028, "Poison": 0xA040A0,
    "Ground": 0xE0C068, "Flying": 0xA890F0, "Psychic": 0xF85888, "Bug": 0xA8B820,
    "Rock": 0xB8A038, "Ghost": 0x705898, "Dragon": 0x7038F8, "Dark": 0x705848,
    "Steel": 0xB8B8D0, "Fairy": 0xEE99AC
}

def get_pokemon_by_rarity(rarity):
    """Get all Pokemon of a specific rarity"""
    return [pokemon for pokemon in POKEMON_DATABASE.values() if pokemon['rarity'] == rarity]

def get_random_pokemon_by_rarity():
    """Get a random Pokemon based on rarity weights"""
    import random
    
    rand = random.random()
    cumulative = 0
    
    for rarity, weight in RARITY_WEIGHTS.items():
        cumulative += weight
        if rand <= cumulative:
            pokemon_list = get_pokemon_by_rarity(rarity)
            if pokemon_list:
                return random.choice(pokemon_list)
    
    # Fallback to common
    common_pokemon = get_pokemon_by_rarity("Common")
    return random.choice(common_pokemon) if common_pokemon else list(POKEMON_DATABASE.values())[0]

def get_pokemon_by_id(pokemon_id):
    """Get Pokemon by its ID"""
    return POKEMON_DATABASE.get(pokemon_id)

def get_pokemon_by_name(name):
    """Get Pokemon by its name"""
    for pokemon in POKEMON_DATABASE.values():
        if pokemon['name'].lower() == name.lower():
            return pokemon
    return None

def get_type_color(pokemon_types):
    """Get the color for a Pokemon based on its primary type"""
    primary_type = pokemon_types[0] if pokemon_types else "Normal"
    return TYPE_COLORS.get(primary_type, 0x000000)

def get_generation_range(generation):
    """Get Pokemon from a specific generation"""
    return [pokemon for pokemon in POKEMON_DATABASE.values() if pokemon['generation'] == generation]

def get_total_pokemon_count():
    """Get total number of Pokemon in database"""
    return len(POKEMON_DATABASE)
