name: Deploy Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-bot
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted, edith]
    steps:
      - name: Run update script
        run: sudo /home/a1h1/update-bot.sh
